kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-pipeline-gitops
  labels:
    app: demo-pipeline-gitops
    app.kubernetes.io/component: demo-pipeline-gitops
    app.kubernetes.io/instance: demo-pipeline-gitops
    app.kubernetes.io/name: demo-pipeline-gitops
    app.kubernetes.io/part-of: demo-pipeline-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-pipeline-gitops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-pipeline-gitops
        deployment: demo-pipeline-gitops
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: demo-pipeline-gitops
          image: 'image-registry.openshift-image-registry.svc:5000/ocp-demo/test-imagestream-gitops:latest'
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
