kind: Service
apiVersion: v1
metadata:
  name: service-github-app
  labels:
    app: deployment-app-github
    app.kubernetes.io/component: deployment-app-github
    app.kubernetes.io/instance: deployment-app-github
    app.kubernetes.io/name: deployment-app-github
    app.kubernetes.io/part-of: deployment-app-github
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: deployment-app-github
    deployment: deployment-app-github
