apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    certificate: |-
{{ .Values.route.tls.certificate | indent 6 }}
    key: |-
{{ .Values.route.tls.key | indent 6 }}
    caCertificate: |-
{{ .Values.route.tls.caCertificate | indent 6 }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}