apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: ocp-demo
spec:
  serviceAccountName: demo-nube
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: registry.redhat.io/ubi9/httpd-24:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pvc-git-demo2
              mountPath: /var/www/html/
      volumes:
        - name: apache-content
          emptyDir: {}
        - name: pvc-git-demo2
          persistentVolumeClaim:
            claimName: pvc-git-demo2
 
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: ocp-demo
spec:
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-route
  namespace: ocp-demo
spec:
  path: /index.html
  to:
    kind: Service
    name: demo-service
  port:
    targetPort: 8080
