# Default values for git-clone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pvc:
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: ""

git:
  hostname: https://github.com/francomdza18/ocp-argo.git
  user: your-username
  pass: your-password
  revision: main
  verbose: true
  sslVerify: true

