kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol-pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-cephfs
  volumeMode: Filesystem